package com.unusualmodding.unusual_prehistory.client.animations.megalania;

import net.minecraft.client.animation.AnimationChannel;
import net.minecraft.client.animation.AnimationDefinition;
import net.minecraft.client.animation.Keyframe;
import net.minecraft.client.animation.KeyframeAnimations;
import net.minecraftforge.api.distmarker.Dist;
import net.minecraftforge.api.distmarker.OnlyIn;

@OnlyIn(Dist.CLIENT)
public class MegalaniaIdleAnimations {

	public static final AnimationDefinition YAWN = AnimationDefinition.Builder.withLength(4.0F)
		.addAnimation("tongue", new AnimationChannel(AnimationChannel.Targets.ROTATION, 
			new Keyframe(0.5F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.5F, KeyframeAnimations.degreeVec(-30.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(4.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM)
		))
		.addAnimation("neck", new AnimationChannel(AnimationChannel.Targets.ROTATION, 
			new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(0.5F, KeyframeAnimations.degreeVec(5.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(0.75F, KeyframeAnimations.degreeVec(-5.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(3.5F, KeyframeAnimations.degreeVec(-7.5F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(4.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM)
		))
		.addAnimation("neck", new AnimationChannel(AnimationChannel.Targets.POSITION, 
			new Keyframe(0.5F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(0.75F, KeyframeAnimations.posVec(0.0F, 0.0F, 1.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(3.5F, KeyframeAnimations.posVec(0.0F, 0.0F, 1.5F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(4.0F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM)
		))
		.addAnimation("head", new AnimationChannel(AnimationChannel.Targets.ROTATION, 
			new Keyframe(0.25F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(0.75F, KeyframeAnimations.degreeVec(10.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.0F, KeyframeAnimations.degreeVec(-20.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(3.4167F, KeyframeAnimations.degreeVec(-30.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(4.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM)
		))
		.addAnimation("head", new AnimationChannel(AnimationChannel.Targets.POSITION, 
			new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(0.75F, KeyframeAnimations.posVec(0.0F, 0.5F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.0F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM)
		))
		.addAnimation("jaw", new AnimationChannel(AnimationChannel.Targets.ROTATION, 
			new Keyframe(0.75F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.0F, KeyframeAnimations.degreeVec(60.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(3.3333F, KeyframeAnimations.degreeVec(80.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(4.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM)
		))
		.build();

	public static final AnimationDefinition TONGUE = AnimationDefinition.Builder.withLength(1.0F)
		.addAnimation("tongue", new AnimationChannel(AnimationChannel.Targets.ROTATION, 
			new Keyframe(0.0417F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(0.0833F, KeyframeAnimations.degreeVec(-19.48F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(0.125F, KeyframeAnimations.degreeVec(-29.22F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(0.1667F, KeyframeAnimations.degreeVec(0.04F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(0.2083F, KeyframeAnimations.degreeVec(37.02F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(0.25F, KeyframeAnimations.degreeVec(35.08F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(0.2917F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(0.3333F, KeyframeAnimations.degreeVec(-31.18F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(0.375F, KeyframeAnimations.degreeVec(-29.23F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(0.4167F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(0.4583F, KeyframeAnimations.degreeVec(25.33F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(0.5F, KeyframeAnimations.degreeVec(23.38F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(0.5417F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(0.5833F, KeyframeAnimations.degreeVec(-19.49F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(0.625F, KeyframeAnimations.degreeVec(-17.54F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(0.6667F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(0.7083F, KeyframeAnimations.degreeVec(13.64F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(0.75F, KeyframeAnimations.degreeVec(11.69F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(0.7917F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(0.8333F, KeyframeAnimations.degreeVec(-7.79F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(0.875F, KeyframeAnimations.degreeVec(-5.85F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(0.9167F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(0.9583F, KeyframeAnimations.degreeVec(1.95F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM)
		))
		.addAnimation("tongue", new AnimationChannel(AnimationChannel.Targets.POSITION, 
			new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(0.0833F, KeyframeAnimations.posVec(0.0F, 0.0F, -9.5F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(0.1667F, KeyframeAnimations.posVec(0.0F, 0.0F, -11.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(0.8333F, KeyframeAnimations.posVec(0.0F, 0.0F, -9.5F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.0F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM)
		))
		.build();

	public static final AnimationDefinition ROAR = AnimationDefinition.Builder.withLength(4.0F)
		.addAnimation("body", new AnimationChannel(AnimationChannel.Targets.ROTATION, 
			new Keyframe(0.5F, KeyframeAnimations.degreeVec(-10.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(0.5625F, KeyframeAnimations.degreeVec(-10.0F, 0.0F, 1.0607F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(0.625F, KeyframeAnimations.degreeVec(-10.0F, 0.0F, -1.5F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(0.6875F, KeyframeAnimations.degreeVec(-10.0F, 0.0F, 1.0607F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(0.8125F, KeyframeAnimations.degreeVec(-10.0F, 0.0F, -1.0607F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(0.875F, KeyframeAnimations.degreeVec(-10.0F, 0.0F, 1.5F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(0.9375F, KeyframeAnimations.degreeVec(-10.0F, 0.0F, -1.0607F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.0F, KeyframeAnimations.degreeVec(-10.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.0313F, KeyframeAnimations.degreeVec(-10.0F, 0.0F, 1.0607F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.0625F, KeyframeAnimations.degreeVec(-10.0F, 0.0F, -1.5F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.0938F, KeyframeAnimations.degreeVec(-10.0F, 0.0F, 1.0607F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.1563F, KeyframeAnimations.degreeVec(-10.0F, 0.0F, -1.0607F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.1875F, KeyframeAnimations.degreeVec(-10.0F, 0.0F, 1.5F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.2188F, KeyframeAnimations.degreeVec(-10.0F, 0.0F, -1.0607F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.2813F, KeyframeAnimations.degreeVec(-10.0F, 0.0F, 1.0607F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.3125F, KeyframeAnimations.degreeVec(-10.0F, 0.0F, -1.5F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.3438F, KeyframeAnimations.degreeVec(-10.0F, 0.0F, 1.0607F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.4063F, KeyframeAnimations.degreeVec(-10.0F, 0.0F, -1.0607F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.4375F, KeyframeAnimations.degreeVec(-10.0F, 0.0F, 1.5F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.4688F, KeyframeAnimations.degreeVec(-10.0F, 0.0F, -1.0607F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.5313F, KeyframeAnimations.degreeVec(-10.0F, 0.0F, 1.0607F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.5625F, KeyframeAnimations.degreeVec(-10.0F, 0.0F, -1.5F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.5938F, KeyframeAnimations.degreeVec(-10.0F, 0.0F, 1.0607F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.6563F, KeyframeAnimations.degreeVec(-10.0F, 0.0F, -1.0607F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.6875F, KeyframeAnimations.degreeVec(-10.0F, 0.0F, 1.5F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.7188F, KeyframeAnimations.degreeVec(-10.0F, 0.0F, -1.0607F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.7813F, KeyframeAnimations.degreeVec(-10.0F, 0.0F, 1.0607F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.8125F, KeyframeAnimations.degreeVec(-10.0F, 0.0F, -1.5F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.8438F, KeyframeAnimations.degreeVec(-10.0F, 0.0F, 1.0607F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.9063F, KeyframeAnimations.degreeVec(-10.0F, 0.0F, -1.0607F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.9375F, KeyframeAnimations.degreeVec(-10.0F, 0.0F, 1.5F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.9688F, KeyframeAnimations.degreeVec(-10.0F, 0.0F, -1.0607F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.0313F, KeyframeAnimations.degreeVec(-10.0F, 0.0F, 1.0607F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.0625F, KeyframeAnimations.degreeVec(-10.0F, 0.0F, -1.5F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.0938F, KeyframeAnimations.degreeVec(-10.0F, 0.0F, 1.0607F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.1563F, KeyframeAnimations.degreeVec(-10.0F, 0.0F, -1.0607F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.1875F, KeyframeAnimations.degreeVec(-10.0F, 0.0F, 1.5F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.2188F, KeyframeAnimations.degreeVec(-10.0F, 0.0F, -1.0607F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.2813F, KeyframeAnimations.degreeVec(-10.0F, 0.0F, 1.0607F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.3125F, KeyframeAnimations.degreeVec(-10.0F, 0.0F, -1.5F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.3438F, KeyframeAnimations.degreeVec(-10.0F, 0.0F, 1.0607F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.4063F, KeyframeAnimations.degreeVec(-10.0F, 0.0F, -1.0607F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.4375F, KeyframeAnimations.degreeVec(-10.0F, 0.0F, 1.5F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.4688F, KeyframeAnimations.degreeVec(-10.0F, 0.0F, -1.0607F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.5313F, KeyframeAnimations.degreeVec(-10.0F, 0.0F, 1.0607F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.5625F, KeyframeAnimations.degreeVec(-10.0F, 0.0F, -1.5F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.5938F, KeyframeAnimations.degreeVec(-10.0F, 0.0F, 1.0607F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.6563F, KeyframeAnimations.degreeVec(-10.0F, 0.0F, -1.0607F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.6875F, KeyframeAnimations.degreeVec(-10.0F, 0.0F, 1.5F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.7188F, KeyframeAnimations.degreeVec(-10.0F, 0.0F, -1.0607F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.7813F, KeyframeAnimations.degreeVec(-10.0F, 0.0F, 1.0607F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.8125F, KeyframeAnimations.degreeVec(-10.0F, 0.0F, -1.5F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.8438F, KeyframeAnimations.degreeVec(-10.0F, 0.0F, 1.0607F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.9063F, KeyframeAnimations.degreeVec(-10.0F, 0.0F, -1.0607F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.9375F, KeyframeAnimations.degreeVec(-10.0F, 0.0F, 1.5F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.9688F, KeyframeAnimations.degreeVec(-10.0F, 0.0F, -1.0607F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(3.0313F, KeyframeAnimations.degreeVec(-10.0F, 0.0F, 1.0607F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(3.0625F, KeyframeAnimations.degreeVec(-10.0F, 0.0F, -1.5F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(3.0938F, KeyframeAnimations.degreeVec(-10.0F, 0.0F, 1.0607F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(3.1563F, KeyframeAnimations.degreeVec(-10.0F, 0.0F, -1.0607F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(3.1875F, KeyframeAnimations.degreeVec(-10.0F, 0.0F, 1.5F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(3.2188F, KeyframeAnimations.degreeVec(-10.0F, 0.0F, -1.0607F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(3.25F, KeyframeAnimations.degreeVec(-10.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(3.3125F, KeyframeAnimations.degreeVec(-10.0F, 0.0F, 1.0607F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(3.375F, KeyframeAnimations.degreeVec(-10.0F, 0.0F, -1.5F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(3.4375F, KeyframeAnimations.degreeVec(-10.0F, 0.0F, 1.0607F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(3.5625F, KeyframeAnimations.degreeVec(-10.0F, 0.0F, -1.0607F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(3.625F, KeyframeAnimations.degreeVec(-10.0F, 0.0F, 1.5F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(3.6875F, KeyframeAnimations.degreeVec(-10.0F, 0.0F, -1.0607F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(3.75F, KeyframeAnimations.degreeVec(-10.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM)
		))
		.addAnimation("body", new AnimationChannel(AnimationChannel.Targets.POSITION, 
			new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, -0.433F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.0F, KeyframeAnimations.posVec(0.0F, 1.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(3.0F, KeyframeAnimations.posVec(0.0F, 1.5F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(4.0F, KeyframeAnimations.posVec(0.0F, -0.433F, 0.0F), AnimationChannel.Interpolations.CATMULLROM)
		))
		.addAnimation("body", new AnimationChannel(AnimationChannel.Targets.SCALE, 
			new Keyframe(3.75F, KeyframeAnimations.scaleVec(1.0F, 1.0F, 1.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(3.8125F, KeyframeAnimations.scaleVec(1.05F, 1.0F, 1.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(3.875F, KeyframeAnimations.scaleVec(1.0F, 0.95F, 1.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(3.9375F, KeyframeAnimations.scaleVec(0.95F, 1.0F, 1.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(4.0F, KeyframeAnimations.scaleVec(1.0F, 1.0F, 1.0F), AnimationChannel.Interpolations.CATMULLROM)
		))
		.addAnimation("neck", new AnimationChannel(AnimationChannel.Targets.ROTATION, 
			new Keyframe(0.0F, KeyframeAnimations.degreeVec(17.8349F, 0.0F, -2.1651F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(0.5F, KeyframeAnimations.degreeVec(5.0F, 18.48F, 1.3F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(0.5625F, KeyframeAnimations.degreeVec(5.0F, 18.83F, -1.45F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(0.625F, KeyframeAnimations.degreeVec(5.0F, 19.14F, 0.75F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(0.6875F, KeyframeAnimations.degreeVec(5.0F, 19.4F, 0.39F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(0.75F, KeyframeAnimations.degreeVec(5.0F, 19.62F, -1.3F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(0.8125F, KeyframeAnimations.degreeVec(5.0F, 19.78F, 1.45F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(0.875F, KeyframeAnimations.degreeVec(5.0F, 19.9F, -0.75F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(0.9375F, KeyframeAnimations.degreeVec(5.0F, 19.98F, -0.39F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.0F, KeyframeAnimations.degreeVec(5.0F, 20.0F, 1.3F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.0313F, KeyframeAnimations.degreeVec(4.79F, 19.98F, -1.45F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.0625F, KeyframeAnimations.degreeVec(4.58F, 19.9F, 0.75F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.0938F, KeyframeAnimations.degreeVec(4.38F, 19.78F, 0.39F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.125F, KeyframeAnimations.degreeVec(4.17F, 19.62F, -1.3F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.1563F, KeyframeAnimations.degreeVec(3.96F, 19.4F, 1.45F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.1875F, KeyframeAnimations.degreeVec(3.75F, 19.14F, -0.75F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.2188F, KeyframeAnimations.degreeVec(3.54F, 18.83F, -0.39F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.25F, KeyframeAnimations.degreeVec(3.33F, 18.48F, 1.3F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.2813F, KeyframeAnimations.degreeVec(3.13F, 18.08F, -1.45F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.3125F, KeyframeAnimations.degreeVec(2.92F, 17.64F, 0.75F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.3438F, KeyframeAnimations.degreeVec(2.71F, 17.15F, 0.39F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.375F, KeyframeAnimations.degreeVec(2.5F, 16.63F, -1.3F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.4063F, KeyframeAnimations.degreeVec(2.29F, 16.06F, 1.45F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.4375F, KeyframeAnimations.degreeVec(2.08F, 15.46F, -0.75F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.4688F, KeyframeAnimations.degreeVec(1.88F, 14.82F, -0.39F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.5F, KeyframeAnimations.degreeVec(1.67F, 14.14F, 1.3F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.5313F, KeyframeAnimations.degreeVec(1.46F, 13.43F, -1.45F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.5625F, KeyframeAnimations.degreeVec(1.25F, 12.69F, 0.75F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.5938F, KeyframeAnimations.degreeVec(1.04F, 11.91F, 0.39F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.625F, KeyframeAnimations.degreeVec(0.83F, 11.11F, -1.3F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.6563F, KeyframeAnimations.degreeVec(0.63F, 10.28F, 1.45F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.6875F, KeyframeAnimations.degreeVec(0.42F, 9.43F, -0.75F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.7188F, KeyframeAnimations.degreeVec(0.21F, 8.55F, -0.39F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.75F, KeyframeAnimations.degreeVec(0.0F, 7.65F, 1.3F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.7813F, KeyframeAnimations.degreeVec(-0.21F, 6.74F, -1.45F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.8125F, KeyframeAnimations.degreeVec(-0.42F, 5.81F, 0.75F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.8438F, KeyframeAnimations.degreeVec(-0.62F, 4.86F, 0.39F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.875F, KeyframeAnimations.degreeVec(-0.83F, 3.9F, -1.3F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.9063F, KeyframeAnimations.degreeVec(-1.04F, 2.93F, 1.45F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.9375F, KeyframeAnimations.degreeVec(-1.25F, 1.96F, -0.75F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.9688F, KeyframeAnimations.degreeVec(-1.46F, 0.98F, -0.39F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.0F, KeyframeAnimations.degreeVec(-1.67F, 0.0F, 1.3F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.0313F, KeyframeAnimations.degreeVec(-1.87F, -0.98F, -1.45F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.0625F, KeyframeAnimations.degreeVec(-2.08F, -1.96F, 0.75F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.0938F, KeyframeAnimations.degreeVec(-2.29F, -2.93F, 0.39F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.125F, KeyframeAnimations.degreeVec(-2.5F, -3.9F, -1.3F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.1563F, KeyframeAnimations.degreeVec(-2.71F, -4.86F, 1.45F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.1875F, KeyframeAnimations.degreeVec(-2.92F, -5.81F, -0.75F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.2188F, KeyframeAnimations.degreeVec(-3.12F, -6.74F, -0.39F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.25F, KeyframeAnimations.degreeVec(-3.33F, -7.65F, 1.3F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.2813F, KeyframeAnimations.degreeVec(-3.54F, -8.55F, -1.45F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.3125F, KeyframeAnimations.degreeVec(-3.75F, -9.43F, 0.75F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.3438F, KeyframeAnimations.degreeVec(-3.96F, -10.28F, 0.39F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.375F, KeyframeAnimations.degreeVec(-4.17F, -11.11F, -1.3F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.4063F, KeyframeAnimations.degreeVec(-4.37F, -11.91F, 1.45F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.4375F, KeyframeAnimations.degreeVec(-4.58F, -12.69F, -0.75F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.4688F, KeyframeAnimations.degreeVec(-4.79F, -13.43F, -0.39F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.5F, KeyframeAnimations.degreeVec(-5.0F, -14.14F, 1.3F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.5313F, KeyframeAnimations.degreeVec(-4.17F, -14.82F, -1.45F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.5625F, KeyframeAnimations.degreeVec(-3.33F, -15.46F, 0.75F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.5938F, KeyframeAnimations.degreeVec(-2.5F, -16.06F, 0.39F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.625F, KeyframeAnimations.degreeVec(-1.67F, -16.63F, -1.3F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.6563F, KeyframeAnimations.degreeVec(-0.83F, -17.15F, 1.45F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.6875F, KeyframeAnimations.degreeVec(0.0F, -17.64F, -0.75F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.7188F, KeyframeAnimations.degreeVec(0.83F, -18.08F, -0.39F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.75F, KeyframeAnimations.degreeVec(1.67F, -18.48F, 1.3F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.7813F, KeyframeAnimations.degreeVec(2.5F, -18.83F, -1.45F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.8125F, KeyframeAnimations.degreeVec(3.33F, -19.14F, 0.75F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.8438F, KeyframeAnimations.degreeVec(4.17F, -19.4F, 0.39F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.875F, KeyframeAnimations.degreeVec(5.0F, -19.62F, -1.3F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.9063F, KeyframeAnimations.degreeVec(5.83F, -19.78F, 1.45F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.9375F, KeyframeAnimations.degreeVec(6.67F, -19.9F, -0.75F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.9688F, KeyframeAnimations.degreeVec(7.5F, -19.98F, -0.39F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(3.0F, KeyframeAnimations.degreeVec(8.33F, -20.0F, 1.3F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(3.0313F, KeyframeAnimations.degreeVec(9.17F, -19.98F, -1.45F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(3.0625F, KeyframeAnimations.degreeVec(10.0F, -19.9F, 0.75F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(3.0938F, KeyframeAnimations.degreeVec(10.83F, -19.78F, 0.39F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(3.125F, KeyframeAnimations.degreeVec(11.67F, -19.62F, -1.3F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(3.1563F, KeyframeAnimations.degreeVec(12.5F, -19.4F, 1.45F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(3.1875F, KeyframeAnimations.degreeVec(13.33F, -19.14F, -0.75F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(3.2188F, KeyframeAnimations.degreeVec(14.17F, -18.83F, -0.39F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(3.25F, KeyframeAnimations.degreeVec(15.0F, -18.48F, 1.3F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(3.3125F, KeyframeAnimations.degreeVec(15.0F, -18.08F, -1.45F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(3.375F, KeyframeAnimations.degreeVec(15.0F, -17.64F, 0.75F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(3.4375F, KeyframeAnimations.degreeVec(15.0F, -17.15F, 0.39F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(3.5F, KeyframeAnimations.degreeVec(15.0F, -16.63F, -1.3F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(3.5625F, KeyframeAnimations.degreeVec(15.0F, -16.06F, 1.45F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(3.625F, KeyframeAnimations.degreeVec(15.0F, -15.46F, -0.75F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(3.6875F, KeyframeAnimations.degreeVec(15.0F, -14.82F, -0.39F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(3.75F, KeyframeAnimations.degreeVec(15.0F, -14.14F, 1.3F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(4.0F, KeyframeAnimations.degreeVec(17.8349F, 0.0F, -2.1651F), AnimationChannel.Interpolations.CATMULLROM)
		))
		.addAnimation("neck", new AnimationChannel(AnimationChannel.Targets.POSITION, 
			new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.0F, KeyframeAnimations.posVec(0.0F, -1.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(3.0F, KeyframeAnimations.posVec(0.0F, -1.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(4.0F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM)
		))
		.addAnimation("head", new AnimationChannel(AnimationChannel.Targets.ROTATION, 
			new Keyframe(0.0F, KeyframeAnimations.degreeVec(-10.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(0.5F, KeyframeAnimations.degreeVec(20.0F, -0.647F, -0.6495F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(0.5625F, KeyframeAnimations.degreeVec(-10.0F, 0.9F, 0.39F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(0.625F, KeyframeAnimations.degreeVec(-10.0F, 1.14F, 0.75F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(0.6875F, KeyframeAnimations.degreeVec(-10.0F, 1.37F, -1.45F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(0.75F, KeyframeAnimations.degreeVec(-10.0F, 1.61F, 1.3F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(0.8125F, KeyframeAnimations.degreeVec(-10.0F, 1.84F, -0.39F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(0.875F, KeyframeAnimations.degreeVec(-10.0F, 2.06F, -0.75F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(0.9375F, KeyframeAnimations.degreeVec(-10.0F, 2.28F, 1.45F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.0F, KeyframeAnimations.degreeVec(-10.0F, 2.5F, -1.3F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.0313F, KeyframeAnimations.degreeVec(-10.47F, 2.71F, 0.39F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.0625F, KeyframeAnimations.degreeVec(-10.94F, 2.91F, 0.75F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.0938F, KeyframeAnimations.degreeVec(-11.41F, 3.11F, -1.45F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.125F, KeyframeAnimations.degreeVec(-11.87F, 3.3F, 1.3F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.1563F, KeyframeAnimations.degreeVec(-12.34F, 3.48F, -0.39F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.1875F, KeyframeAnimations.degreeVec(-12.81F, 3.65F, -0.75F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.2188F, KeyframeAnimations.degreeVec(-13.28F, 3.81F, 1.45F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.25F, KeyframeAnimations.degreeVec(-13.75F, 3.97F, -1.3F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.2813F, KeyframeAnimations.degreeVec(-14.22F, 4.11F, 0.39F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.3125F, KeyframeAnimations.degreeVec(-14.69F, 4.25F, 0.75F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.3438F, KeyframeAnimations.degreeVec(-15.16F, 4.37F, -1.45F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.375F, KeyframeAnimations.degreeVec(-15.62F, 4.48F, 1.3F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.4063F, KeyframeAnimations.degreeVec(-16.09F, 4.59F, -0.39F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.4375F, KeyframeAnimations.degreeVec(-16.56F, 4.68F, -0.75F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.4688F, KeyframeAnimations.degreeVec(-17.03F, 4.76F, 1.45F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.5F, KeyframeAnimations.degreeVec(-17.5F, 4.83F, -1.3F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.5313F, KeyframeAnimations.degreeVec(-17.97F, 4.89F, 0.39F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.5625F, KeyframeAnimations.degreeVec(-18.44F, 4.93F, 0.75F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.5938F, KeyframeAnimations.degreeVec(-18.91F, 4.97F, -1.45F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.625F, KeyframeAnimations.degreeVec(-19.37F, 4.99F, 1.3F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.6563F, KeyframeAnimations.degreeVec(-19.84F, 5.0F, -0.39F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.6875F, KeyframeAnimations.degreeVec(-20.31F, 5.0F, -0.75F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.7188F, KeyframeAnimations.degreeVec(-20.78F, 4.98F, 1.45F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.75F, KeyframeAnimations.degreeVec(-21.25F, 4.96F, -1.3F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.7813F, KeyframeAnimations.degreeVec(-21.72F, 4.92F, 0.39F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.8125F, KeyframeAnimations.degreeVec(-22.19F, 4.87F, 0.75F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.8438F, KeyframeAnimations.degreeVec(-22.66F, 4.81F, -1.45F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.875F, KeyframeAnimations.degreeVec(-23.12F, 4.73F, 1.3F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.9063F, KeyframeAnimations.degreeVec(-23.59F, 4.65F, -0.39F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.9375F, KeyframeAnimations.degreeVec(-24.06F, 4.55F, -0.75F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.9688F, KeyframeAnimations.degreeVec(-24.53F, 4.45F, 1.45F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.0F, KeyframeAnimations.degreeVec(-25.0F, 4.33F, -1.3F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.0313F, KeyframeAnimations.degreeVec(-25.47F, 4.2F, 0.39F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.0625F, KeyframeAnimations.degreeVec(-25.94F, 4.06F, 0.75F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.0938F, KeyframeAnimations.degreeVec(-26.41F, 3.92F, -1.45F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.125F, KeyframeAnimations.degreeVec(-26.87F, 3.76F, 1.3F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.1563F, KeyframeAnimations.degreeVec(-27.34F, 3.59F, -0.39F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.1875F, KeyframeAnimations.degreeVec(-27.81F, 3.42F, -0.75F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.2188F, KeyframeAnimations.degreeVec(-28.28F, 3.23F, 1.45F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.25F, KeyframeAnimations.degreeVec(-28.75F, 3.04F, -1.3F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.2813F, KeyframeAnimations.degreeVec(-29.22F, 2.85F, 0.39F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.3125F, KeyframeAnimations.degreeVec(-29.69F, 2.64F, 0.75F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.3438F, KeyframeAnimations.degreeVec(-30.16F, 2.43F, -1.45F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.375F, KeyframeAnimations.degreeVec(-30.62F, 2.21F, 1.3F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.4063F, KeyframeAnimations.degreeVec(-31.09F, 1.99F, -0.39F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.4375F, KeyframeAnimations.degreeVec(-31.56F, 1.76F, -0.75F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.4688F, KeyframeAnimations.degreeVec(-32.03F, 1.53F, 1.45F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.5F, KeyframeAnimations.degreeVec(-32.5F, 1.29F, -1.3F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.5313F, KeyframeAnimations.degreeVec(-32.97F, 1.06F, 0.39F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.5625F, KeyframeAnimations.degreeVec(-33.44F, 0.81F, 0.75F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.5938F, KeyframeAnimations.degreeVec(-33.91F, 0.57F, -1.45F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.625F, KeyframeAnimations.degreeVec(-34.37F, 0.33F, 1.3F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.6563F, KeyframeAnimations.degreeVec(-34.84F, 0.08F, -0.39F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.6875F, KeyframeAnimations.degreeVec(-35.31F, -0.16F, -0.75F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.7188F, KeyframeAnimations.degreeVec(-35.78F, -0.41F, 1.45F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.75F, KeyframeAnimations.degreeVec(-36.25F, -0.65F, -1.3F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.7813F, KeyframeAnimations.degreeVec(-36.72F, -0.9F, 0.39F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.8125F, KeyframeAnimations.degreeVec(-37.19F, -1.14F, 0.75F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.8438F, KeyframeAnimations.degreeVec(-37.66F, -1.37F, -1.45F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.875F, KeyframeAnimations.degreeVec(-38.12F, -1.61F, 1.3F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.9063F, KeyframeAnimations.degreeVec(-38.59F, -1.84F, -0.39F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.9375F, KeyframeAnimations.degreeVec(-39.06F, -2.06F, -0.75F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.9688F, KeyframeAnimations.degreeVec(-39.53F, -2.28F, 1.45F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(3.0F, KeyframeAnimations.degreeVec(-40.0F, -2.5F, -1.3F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(3.0313F, KeyframeAnimations.degreeVec(-39.5F, -2.71F, 0.39F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(3.0625F, KeyframeAnimations.degreeVec(-39.0F, -2.91F, 0.75F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(3.0938F, KeyframeAnimations.degreeVec(-38.51F, -3.11F, -1.45F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(3.125F, KeyframeAnimations.degreeVec(-38.01F, -3.3F, 1.3F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(3.1563F, KeyframeAnimations.degreeVec(-37.51F, -3.48F, -0.39F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(3.1875F, KeyframeAnimations.degreeVec(-37.01F, -3.65F, -0.75F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(3.2188F, KeyframeAnimations.degreeVec(-36.51F, -3.81F, 1.45F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(3.25F, KeyframeAnimations.degreeVec(-36.02F, -3.97F, -1.3F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(3.3125F, KeyframeAnimations.degreeVec(-36.02F, -4.11F, 0.39F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(3.375F, KeyframeAnimations.degreeVec(-36.02F, -4.25F, 0.75F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(3.4375F, KeyframeAnimations.degreeVec(-36.02F, -4.37F, -1.45F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(3.5F, KeyframeAnimations.degreeVec(-36.02F, -4.48F, 1.3F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(3.5625F, KeyframeAnimations.degreeVec(-36.02F, -4.59F, -0.39F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(3.625F, KeyframeAnimations.degreeVec(-36.02F, -4.68F, -0.75F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(3.6875F, KeyframeAnimations.degreeVec(-36.02F, -4.76F, 1.45F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(3.75F, KeyframeAnimations.degreeVec(-36.02F, -4.83F, -1.3F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(4.0F, KeyframeAnimations.degreeVec(-10.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM)
		))
		.addAnimation("head", new AnimationChannel(AnimationChannel.Targets.POSITION, 
			new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.0F, KeyframeAnimations.posVec(0.0F, 0.0F, -1.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(3.0F, KeyframeAnimations.posVec(0.0F, 0.0F, -1.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(4.0F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM)
		))
		.addAnimation("tail1", new AnimationChannel(AnimationChannel.Targets.ROTATION, 
			new Keyframe(0.0F, KeyframeAnimations.degreeVec(-2.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(0.25F, KeyframeAnimations.degreeVec(-7.5F, 3.75F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(0.5F, KeyframeAnimations.degreeVec(-5.0F, 7.5F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(0.75F, KeyframeAnimations.degreeVec(13.0F, 7.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.0F, KeyframeAnimations.degreeVec(35.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.0625F, KeyframeAnimations.degreeVec(35.56F, -2.9264F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.125F, KeyframeAnimations.degreeVec(36.11F, -5.7403F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.1875F, KeyframeAnimations.degreeVec(36.67F, -8.3336F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.25F, KeyframeAnimations.degreeVec(37.22F, -10.6066F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.3125F, KeyframeAnimations.degreeVec(37.78F, -12.472F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.375F, KeyframeAnimations.degreeVec(38.33F, -13.8582F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.4375F, KeyframeAnimations.degreeVec(38.89F, -14.7118F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.5F, KeyframeAnimations.degreeVec(39.44F, -15.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.5625F, KeyframeAnimations.degreeVec(39.99F, -14.7118F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.625F, KeyframeAnimations.degreeVec(40.55F, -13.8582F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.6875F, KeyframeAnimations.degreeVec(41.11F, -12.472F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.75F, KeyframeAnimations.degreeVec(41.66F, -10.6066F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.8125F, KeyframeAnimations.degreeVec(42.22F, -8.3336F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.875F, KeyframeAnimations.degreeVec(42.77F, -5.7403F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.125F, KeyframeAnimations.degreeVec(45.0F, 5.7403F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.1875F, KeyframeAnimations.degreeVec(44.86F, 8.3336F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.25F, KeyframeAnimations.degreeVec(44.72F, 10.6066F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.3125F, KeyframeAnimations.degreeVec(44.58F, 12.472F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.375F, KeyframeAnimations.degreeVec(44.44F, 13.8582F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.4375F, KeyframeAnimations.degreeVec(44.3F, 14.7118F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.5F, KeyframeAnimations.degreeVec(44.16F, 15.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.5625F, KeyframeAnimations.degreeVec(44.02F, 14.7118F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.625F, KeyframeAnimations.degreeVec(43.88F, 13.8582F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.6875F, KeyframeAnimations.degreeVec(43.74F, 12.472F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.75F, KeyframeAnimations.degreeVec(43.6F, 10.6066F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.8125F, KeyframeAnimations.degreeVec(43.47F, 8.3336F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.875F, KeyframeAnimations.degreeVec(43.33F, 5.7403F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(3.125F, KeyframeAnimations.degreeVec(42.78F, -5.7403F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(3.1875F, KeyframeAnimations.degreeVec(42.64F, -8.3336F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(3.25F, KeyframeAnimations.degreeVec(42.0F, -10.6066F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(3.375F, KeyframeAnimations.degreeVec(35.0F, -12.472F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(3.5F, KeyframeAnimations.degreeVec(25.0F, -13.8582F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(3.625F, KeyframeAnimations.degreeVec(10.0F, -13.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(3.75F, KeyframeAnimations.degreeVec(2.5F, -9.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(3.875F, KeyframeAnimations.degreeVec(-2.5F, -2.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(4.0F, KeyframeAnimations.degreeVec(-2.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM)
		))
		.addAnimation("tail1", new AnimationChannel(AnimationChannel.Targets.POSITION, 
			new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, 0.5F, 0.0F), AnimationChannel.Interpolations.CATMULLROM)
		))
		.addAnimation("tail2", new AnimationChannel(AnimationChannel.Targets.ROTATION, 
			new Keyframe(0.0F, KeyframeAnimations.degreeVec(12.0F, -12.9904F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(0.5F, KeyframeAnimations.degreeVec(5.0F, 2.5048F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(0.625F, KeyframeAnimations.degreeVec(5.5F, 10.5F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(0.75F, KeyframeAnimations.degreeVec(6.75F, 17.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(0.875F, KeyframeAnimations.degreeVec(8.0F, 18.9386F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.0F, KeyframeAnimations.degreeVec(9.0F, 17.3205F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.0625F, KeyframeAnimations.degreeVec(9.5F, 15.0368F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.125F, KeyframeAnimations.degreeVec(10.0F, 12.1752F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.1875F, KeyframeAnimations.degreeVec(10.0F, 8.8458F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.25F, KeyframeAnimations.degreeVec(10.0F, 5.1764F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.375F, KeyframeAnimations.degreeVec(10.0F, -2.6105F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.4375F, KeyframeAnimations.degreeVec(10.0F, -6.4288F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.5F, KeyframeAnimations.degreeVec(10.0F, -10.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.5625F, KeyframeAnimations.degreeVec(10.0F, -13.1869F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.625F, KeyframeAnimations.degreeVec(10.0F, -15.8671F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.6875F, KeyframeAnimations.degreeVec(10.0F, -17.9375F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.75F, KeyframeAnimations.degreeVec(10.0F, -19.3185F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.8125F, KeyframeAnimations.degreeVec(10.0F, -19.9572F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.875F, KeyframeAnimations.degreeVec(10.0F, -19.8289F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.9375F, KeyframeAnimations.degreeVec(10.0F, -18.9386F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.0F, KeyframeAnimations.degreeVec(10.0F, -17.3205F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.0625F, KeyframeAnimations.degreeVec(10.0F, -15.0368F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.125F, KeyframeAnimations.degreeVec(10.0F, -12.1752F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.1875F, KeyframeAnimations.degreeVec(10.0F, -8.8458F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.25F, KeyframeAnimations.degreeVec(10.0F, -5.1764F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.375F, KeyframeAnimations.degreeVec(10.0F, 2.6105F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.4375F, KeyframeAnimations.degreeVec(10.0F, 6.4288F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.5F, KeyframeAnimations.degreeVec(10.0F, 10.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.5625F, KeyframeAnimations.degreeVec(10.0F, 13.1869F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.625F, KeyframeAnimations.degreeVec(10.0F, 15.8671F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.6875F, KeyframeAnimations.degreeVec(10.0F, 17.9375F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.75F, KeyframeAnimations.degreeVec(10.0F, 19.3185F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.8125F, KeyframeAnimations.degreeVec(10.0F, 19.9572F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.875F, KeyframeAnimations.degreeVec(10.0F, 19.8289F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.9375F, KeyframeAnimations.degreeVec(10.0F, 18.9386F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(3.0F, KeyframeAnimations.degreeVec(10.0F, 17.3205F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(3.0625F, KeyframeAnimations.degreeVec(10.0F, 15.0368F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(3.125F, KeyframeAnimations.degreeVec(10.0F, 12.1752F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(3.1875F, KeyframeAnimations.degreeVec(10.0F, 8.8458F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(3.25F, KeyframeAnimations.degreeVec(10.0F, 5.1764F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(3.375F, KeyframeAnimations.degreeVec(10.0F, -2.5F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(3.5F, KeyframeAnimations.degreeVec(10.0F, -10.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(3.625F, KeyframeAnimations.degreeVec(10.0F, -17.5F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(3.875F, KeyframeAnimations.degreeVec(10.0F, -20.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(4.0F, KeyframeAnimations.degreeVec(12.0F, -12.9904F, 0.0F), AnimationChannel.Interpolations.CATMULLROM)
		))
		.addAnimation("left_arm1", new AnimationChannel(AnimationChannel.Targets.ROTATION, 
			new Keyframe(0.5F, KeyframeAnimations.degreeVec(0.0F, 20.0F, -20.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.0F, KeyframeAnimations.degreeVec(30.0F, -30.0F, -15.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(3.0F, KeyframeAnimations.degreeVec(30.0F, -30.0F, -15.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(3.75F, KeyframeAnimations.degreeVec(10.0F, 20.0F, -15.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(4.0F, KeyframeAnimations.degreeVec(0.0F, 20.0F, -20.0F), AnimationChannel.Interpolations.CATMULLROM)
		))
		.addAnimation("left_arm1", new AnimationChannel(AnimationChannel.Targets.POSITION, 
			new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, 0.0F, 1.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(0.5F, KeyframeAnimations.posVec(0.0F, 2.0F, 1.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.0F, KeyframeAnimations.posVec(0.0F, 0.0F, 1.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(3.0F, KeyframeAnimations.posVec(0.0F, 0.0F, 1.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(3.75F, KeyframeAnimations.posVec(0.0F, -1.0F, 1.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(4.0F, KeyframeAnimations.posVec(0.0F, 0.0F, 1.0F), AnimationChannel.Interpolations.CATMULLROM)
		))
		.addAnimation("left_arm1", new AnimationChannel(AnimationChannel.Targets.SCALE, 
			new Keyframe(3.75F, KeyframeAnimations.scaleVec(1.0F, 1.0F, 1.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(3.8125F, KeyframeAnimations.scaleVec(1.1F, 1.0F, 1.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(3.875F, KeyframeAnimations.scaleVec(1.0F, 1.0F, 0.9F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(3.9375F, KeyframeAnimations.scaleVec(0.9F, 1.0F, 1.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(4.0F, KeyframeAnimations.scaleVec(1.0F, 1.0F, 1.0F), AnimationChannel.Interpolations.CATMULLROM)
		))
		.addAnimation("left_arm2", new AnimationChannel(AnimationChannel.Targets.ROTATION, 
			new Keyframe(0.5F, KeyframeAnimations.degreeVec(-20.0F, -25.0F, 22.5F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.0F, KeyframeAnimations.degreeVec(120.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(3.0F, KeyframeAnimations.degreeVec(120.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(3.75F, KeyframeAnimations.degreeVec(-20.0F, -25.0F, 22.5F), AnimationChannel.Interpolations.CATMULLROM)
		))
		.addAnimation("right_arm1", new AnimationChannel(AnimationChannel.Targets.ROTATION, 
			new Keyframe(0.5F, KeyframeAnimations.degreeVec(-20.0F, -20.0F, 30.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.0F, KeyframeAnimations.degreeVec(30.0F, 30.0F, 15.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(3.0F, KeyframeAnimations.degreeVec(30.0F, 30.0F, 15.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(3.75F, KeyframeAnimations.degreeVec(-10.0F, -20.0F, 20.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(4.0F, KeyframeAnimations.degreeVec(-20.0F, -20.0F, 30.0F), AnimationChannel.Interpolations.CATMULLROM)
		))
		.addAnimation("right_arm1", new AnimationChannel(AnimationChannel.Targets.POSITION, 
			new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(0.5F, KeyframeAnimations.posVec(0.0F, 2.5F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.0F, KeyframeAnimations.posVec(0.0F, 0.0F, 1.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(3.0F, KeyframeAnimations.posVec(0.0F, 0.0F, 1.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(3.75F, KeyframeAnimations.posVec(0.0F, -1.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(4.0F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM)
		))
		.addAnimation("right_arm1", new AnimationChannel(AnimationChannel.Targets.SCALE, 
			new Keyframe(3.75F, KeyframeAnimations.scaleVec(1.0F, 1.0F, 1.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(3.8125F, KeyframeAnimations.scaleVec(1.1F, 1.0F, 1.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(3.875F, KeyframeAnimations.scaleVec(1.0F, 1.0F, 0.9F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(3.9375F, KeyframeAnimations.scaleVec(0.9F, 1.0F, 1.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(4.0F, KeyframeAnimations.scaleVec(1.0F, 1.0F, 1.0F), AnimationChannel.Interpolations.CATMULLROM)
		))
		.addAnimation("right_arm2", new AnimationChannel(AnimationChannel.Targets.ROTATION, 
			new Keyframe(0.5F, KeyframeAnimations.degreeVec(7.5F, 50.0F, -20.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.0F, KeyframeAnimations.degreeVec(120.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(3.0F, KeyframeAnimations.degreeVec(120.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(3.75F, KeyframeAnimations.degreeVec(7.5F, 35.0F, -17.5F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(4.0F, KeyframeAnimations.degreeVec(7.5F, 50.0F, -20.0F), AnimationChannel.Interpolations.CATMULLROM)
		))
		.addAnimation("left_leg1", new AnimationChannel(AnimationChannel.Targets.ROTATION, 
			new Keyframe(0.0F, KeyframeAnimations.degreeVec(20.0F, -20.0F, -31.25F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.0F, KeyframeAnimations.degreeVec(10.0F, -20.0F, -31.25F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(4.0F, KeyframeAnimations.degreeVec(20.0F, -20.0F, -31.25F), AnimationChannel.Interpolations.CATMULLROM)
		))
		.addAnimation("left_leg1", new AnimationChannel(AnimationChannel.Targets.POSITION, 
			new Keyframe(0.0F, KeyframeAnimations.posVec(-0.25F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.0F, KeyframeAnimations.posVec(-0.25F, 0.0F, 1.5F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(4.0F, KeyframeAnimations.posVec(-0.25F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM)
		))
		.addAnimation("left_leg2", new AnimationChannel(AnimationChannel.Targets.ROTATION, 
			new Keyframe(0.0F, KeyframeAnimations.degreeVec(-15.0F, -30.0F, 32.5F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.0F, KeyframeAnimations.degreeVec(-5.0F, -30.0F, 30.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(4.0F, KeyframeAnimations.degreeVec(-15.0F, -30.0F, 32.5F), AnimationChannel.Interpolations.CATMULLROM)
		))
		.addAnimation("right_leg1", new AnimationChannel(AnimationChannel.Targets.ROTATION, 
			new Keyframe(0.0F, KeyframeAnimations.degreeVec(10.0F, 20.0F, 31.25F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.0F, KeyframeAnimations.degreeVec(20.0F, 20.0F, 31.25F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(4.0F, KeyframeAnimations.degreeVec(10.0F, 20.0F, 31.25F), AnimationChannel.Interpolations.CATMULLROM)
		))
		.addAnimation("right_leg1", new AnimationChannel(AnimationChannel.Targets.POSITION, 
			new Keyframe(0.0F, KeyframeAnimations.posVec(0.25F, 0.0F, -2.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.0F, KeyframeAnimations.posVec(0.25F, 0.5F, -2.5F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(4.0F, KeyframeAnimations.posVec(0.25F, 0.0F, -2.0F), AnimationChannel.Interpolations.CATMULLROM)
		))
		.addAnimation("right_leg2", new AnimationChannel(AnimationChannel.Targets.ROTATION, 
			new Keyframe(0.0F, KeyframeAnimations.degreeVec(-7.5F, 15.0F, -30.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.0F, KeyframeAnimations.degreeVec(-10.0F, 10.0F, -30.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(4.0F, KeyframeAnimations.degreeVec(-7.5F, 15.0F, -30.0F), AnimationChannel.Interpolations.CATMULLROM)
		))
		.addAnimation("tail3", new AnimationChannel(AnimationChannel.Targets.ROTATION, 
			new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, -17.3205F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(0.5F, KeyframeAnimations.degreeVec(0.0F, -7.5295F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(0.625F, KeyframeAnimations.degreeVec(0.0F, -1.9428F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(0.75F, KeyframeAnimations.degreeVec(0.0F, 7.219F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(0.875F, KeyframeAnimations.degreeVec(0.0F, 16.796F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.0625F, KeyframeAnimations.degreeVec(0.0F, 24.6733F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.1875F, KeyframeAnimations.degreeVec(0.0F, 24.9465F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.25F, KeyframeAnimations.degreeVec(0.0F, 24.1481F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.3125F, KeyframeAnimations.degreeVec(0.0F, 22.4218F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.375F, KeyframeAnimations.degreeVec(0.0F, 19.8338F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.4375F, KeyframeAnimations.degreeVec(0.0F, 16.4836F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.5F, KeyframeAnimations.degreeVec(0.0F, 12.5F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.5625F, KeyframeAnimations.degreeVec(0.0F, 8.036F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.6875F, KeyframeAnimations.degreeVec(0.0F, -1.6351F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.75F, KeyframeAnimations.degreeVec(0.0F, -6.4705F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.8125F, KeyframeAnimations.degreeVec(0.0F, -11.0572F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.875F, KeyframeAnimations.degreeVec(0.0F, -15.219F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.9375F, KeyframeAnimations.degreeVec(0.0F, -18.796F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.0F, KeyframeAnimations.degreeVec(0.0F, -21.6506F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.0625F, KeyframeAnimations.degreeVec(0.0F, -23.6733F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.125F, KeyframeAnimations.degreeVec(0.0F, -24.7861F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.1875F, KeyframeAnimations.degreeVec(0.0F, -24.9465F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.25F, KeyframeAnimations.degreeVec(0.0F, -24.1481F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.3125F, KeyframeAnimations.degreeVec(0.0F, -22.4218F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.375F, KeyframeAnimations.degreeVec(0.0F, -19.8338F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.4375F, KeyframeAnimations.degreeVec(0.0F, -16.4836F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.5F, KeyframeAnimations.degreeVec(0.0F, -12.5F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.5625F, KeyframeAnimations.degreeVec(0.0F, -8.036F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.6875F, KeyframeAnimations.degreeVec(0.0F, 1.6351F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.75F, KeyframeAnimations.degreeVec(0.0F, 6.4705F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.8125F, KeyframeAnimations.degreeVec(0.0F, 11.0572F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.875F, KeyframeAnimations.degreeVec(0.0F, 15.219F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.9375F, KeyframeAnimations.degreeVec(0.0F, 18.796F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(3.0F, KeyframeAnimations.degreeVec(0.0F, 21.6506F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(3.0625F, KeyframeAnimations.degreeVec(0.0F, 23.6733F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(3.125F, KeyframeAnimations.degreeVec(0.0F, 24.7861F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(3.1875F, KeyframeAnimations.degreeVec(0.0F, 24.9465F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(3.25F, KeyframeAnimations.degreeVec(0.0F, 24.1481F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(3.5F, KeyframeAnimations.degreeVec(0.0F, 19.8338F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(3.625F, KeyframeAnimations.degreeVec(0.0F, 12.4836F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(3.75F, KeyframeAnimations.degreeVec(0.0F, 0.5F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(4.0F, KeyframeAnimations.degreeVec(0.0F, -17.3205F, 0.0F), AnimationChannel.Interpolations.CATMULLROM)
		))
		.addAnimation("body_upper", new AnimationChannel(AnimationChannel.Targets.ROTATION, 
			new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(0.5F, KeyframeAnimations.degreeVec(5.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.0F, KeyframeAnimations.degreeVec(-35.0F, 5.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(3.25F, KeyframeAnimations.degreeVec(-40.0F, -5.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(3.75F, KeyframeAnimations.degreeVec(-5.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(4.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM)
		))
		.addAnimation("jaw", new AnimationChannel(AnimationChannel.Targets.ROTATION, 
			new Keyframe(0.75F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.0F, KeyframeAnimations.degreeVec(10.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(3.0F, KeyframeAnimations.degreeVec(80.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(4.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM)
		))
		.addAnimation("tongue", new AnimationChannel(AnimationChannel.Targets.ROTATION, 
			new Keyframe(0.5F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.5F, KeyframeAnimations.degreeVec(-30.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(4.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM)
		))
		.build();
}